11-MVC_StatedManagement_Session/Models/ErrorViewModel.cs
namespace _17_MVC_StatedManagement_Session.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

11-MVC_StatedManagement_Session/Controllers/CerezController.cs
using Microsoft.AspNetCore.Mvc;

namespace _17_MVC_StatedManagement_Session.Controllers
{
    public class CerezController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Response.Cookies.Append("Ad", "Bilge Adam");
            HttpContext.Response.Cookies.Append("personelYasi", "25");
            HttpContext.Response.Cookies.Append("personelMaili", "bilge@bilgeadam.com");
            HttpContext.Response.Cookies.Append("personelRolu", "kullanıcı");
           
            return View();
        }
        public IActionResult Cerez()
        {
            string ad = CerezGetir("Ad");
            string personelYasi = CerezGetir("personelYasi");
            string personelMaili = CerezGetir("personelMaili");
            string personelRolü = CerezGetir("personelRolü");

            ViewBag.prsAdi = ad;
            ViewBag.prsYasi = personelYasi;
            ViewBag.prs.Maili=personelMaili;
            ViewBag.prsRolu = personelRolü;

            return View();
        }
        private string CerezGetir(string key)
        {
             HttpContext.Request.Cookies.TryGetValue(key, out string value);
            return value;
        }
    }
}

11-MVC_StatedManagement_Session/Controllers/HomeController.cs
using _17_MVC_StatedManagement_Session.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace _17_MVC_StatedManagement_Session.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

11-MVC_StatedManagement_Session/Controllers/OturumController.cs
using Microsoft.AspNetCore.Mvc;

namespace _17_MVC_StatedManagement_Session.Controllers
{
    public class OturumController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.SetString("ad", "Bilge Adam");
            HttpContext.Session.SetInt32("personelYasi", 18);
            HttpContext.Session.SetString("personelMaili", "bilge@bilgeadam.com");
            HttpContext.Session.SetString("personelRolu", "kullanici");

            return View();
        }
        public IActionResult Oturum()
        {
            ViewBag.prsAdi = HttpContext.Session.GetString("AD");
            ViewBag.prsAdi = HttpContext.Session.GetString("personelYasi");
            ViewBag.prsAdi = HttpContext.Session.GetString("personelMaili");
            ViewBag.prsAdi = HttpContext.Session.GetString("personelRolü");
            return View();
        }
    }
}

11-MVC_StatedManagement_Session/Views/Cerez/Cerez.cshtml
<h1>Çerez</h1>
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3>Oturum Bilgileri</h3>
            </div>
            <div class="card-body">
                <label><b>Personel Adı:</b> @ViewBag.prsAdi</label><br />
                <label><b>Personel Yaşı:</b> @ViewBag.prsYasi</label><br />
                <label><b>Personel Maili:</b> @ViewBag.prsMaili</label><br />
                <label><b>Personel Rolu:</b> @ViewBag.prsRolu</label><br />
            </div>

            <div class="card-footer">
                <a class="btn btn-warning btn-block" asp-controller="Oturum" asp-action="Index">Geri Dön</a>

            </div>
        </div>

    </div>
</div>

11-MVC_StatedManagement_Session/Views/Cerez/Index.cshtml
<h1>Index</h1>
<h3>Cookie oluşturuldu.Sonuçları görmek için Cookie sayfasına gidiniz...</h3>
<br />
<br />
<a class="btn btn-success" asp-action="Cerez">Cerez sayfasına gitmek için tıklatınız...</a>

11-MVC_StatedManagement_Session/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

11-MVC_StatedManagement_Session/Views/Oturum/Index.cshtml
<h1>Index</h1>

<h3>Sesion oluşturuldu. Sonuçları görmek için Oturum sayfasına gidiniz..</h3>

<a asp-action="Oturum" asp-controller="Oturum" class="btn btn-success">Oturum sayfasına gitmek için tıklayınız..</a>

11-MVC_StatedManagement_Session/Views/Oturum/Oturum.cshtml
<h1>Oturum</h1>

<div>
    <h4>View'dan ilgili Session'daki bilgiye ulaşmak için:</h4>
</div>

<p>@Context.Session.GetString("ad")</p>

<p>
    @if (Context.Session.GetString("rol") == "yonetici")
    {
        <b>Bu kullanıcı yöneticidir.</b>
    }
    else
    {
        <b>Bu kullanıcı yönetici değildir.</b>
    }
</p>

11-MVC_StatedManagement_Session/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _17_MVC_StatedManagement_Session</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_17_MVC_StatedManagement_Session.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_17_MVC_StatedManagement_Session</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - _17_MVC_StatedManagement_Session - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>